(define converte-Fahnrenheit
  (lambda(f)
    (define c (* (- f 32) (/ 5 9 )))
    (define k (+ f 273.16))
    (display "Fahrenheit: ")
    (display f)
    (newline)
    (display "Centígrados: ")
    (display c)
    (newline)
    (display "Kelvin: ")
    (display k)
    ))